package simple;
import java.util.HashMap;
import java.util.Map;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * @author Dian
 *
 */
public class FindDifference_389 {
	public char findTheDifference(String s, String t) {
	    Map<Character, Integer> smap=new HashMap<Character, Integer>();
	    Map<Character, Integer> tmap=new HashMap<Character, Integer>();
	    char ch,c = 0;
	    //鏋勫缓涓や釜map
	    for(int i=0;i<t.length();i++){
	    	if(i<t.length()-1){
	    		ch=s.charAt(i);
	    		if(smap.containsKey(ch)){
	    			smap.put(ch, (int)smap.get(ch)+1);
	    		}else{
	    			smap.put(ch, 1);
	    		}
	    		
	    		ch=t.charAt(i);
	    		if(tmap.containsKey(ch)){
	    			tmap.put(ch, (int)tmap.get(ch)+1);
	    		}else{
	    			tmap.put(ch, 1);
	    		}
	    	}else{
	    		ch=t.charAt(i);
	    		if(tmap.containsKey(ch)){
	    			tmap.put(ch, (int)tmap.get(ch)+1);
	    		}else{
	    			tmap.put(ch, 1);
	    		}
	    	}
	    }
	    
	    //閬嶅巻tmap锛屾壘涓嶅悓
	    for(Map.Entry<Character, Integer> entry : tmap.entrySet()){
	    	c =entry.getKey();
	    	if(!smap.containsKey(c)){
	    		return c;
	    	}else{
	    		if(tmap.get(c)!=smap.get(c)){
	    			return c;
	    		}
	    	}
	    }
	    return c;
	}
	
	//鏉ヨ嚜璁ㄨ鍖虹瓟妗?1---鍒╃敤浜︽垨
	public char findTheDifference1(String s, String t) {
		char c=0;
		for(int i=0;i<s.length();i++){
			c^=s.charAt(i);
			c^=t.charAt(i);
		}
		c^=t.charAt(t.length()-1);//t鐨勬渶鍚庝竴涓瓧绗?
		return c;
	}
	
	//鏉ヨ嚜璁ㄨ鍖虹殑绛旀2---鍒╃敤char鐨勬暣鏁板?硷紝璁＄畻t鍜宻鐨勫悇涓暣鏁板?间箣鍜岋紝璁＄畻宸?煎嵆鍙?
	public char findTheDifference2(String s, String t) {
		int ssum=0,tsum=0;
		for(int i=0;i<s.length();i++){
			ssum+=s.charAt(i);
			tsum+=t.charAt(i);
		}
		tsum+=t.charAt(t.length()-1);
		return (char)(tsum-ssum);
	}
}
